from database import engine, SessionLocal
from fastapi import FastAPI,Depends
from schemas import TelemetryCreate, Patient_input, Patient_output
from sqlalchemy.orm import Session
from typing import TypedDict
import models
from vector_db import vector_db, collection
import ollama #type:ignore
from langgraph.graph import StateGraph, END


#node 1 getting patient numerical_data based on the patient id
#node 2 getting the unstructured patient data and doctors remarks 
#node 3 getting the llm medical recommendation using llama
models.Base.metadata.create_all(bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

class GraphState(TypedDict):
    patient_id: str
    question: str
    heart_beat: float
    systolic_bp: float
    Patient_status: str
    llm_recommendation: str


    

def get_patient_structured_data(payload:GraphState):
    print(f"[System-log] fetching structured data for {payload['patient_id']}")

    db= SessionLocal() 
    patient_data = db.query(models.patienttelementery)\
    .filter(models.patienttelementery.patient_id == payload['patient_id'] ) \
    .first()
    if patient_data:
        return {'heart_beat':patient_data.heart_rate,'systolic_bp':patient_data.systolic_bp}
    else:
        return {'heart_beat':0, 'systolic_bp':0}
    
def get_patient_unstructured_data(payload:GraphState):
    print(f"[System-log] extracting the unstructured data about patient {payload['patient_id']}")
    response = collection.query(
        query_texts= [payload['question']],
        n_results=1,
        where = {'patient_id':payload['patient_id']} 
    )
    print('[System-log] Query is in progress')

    return {'Patient_status': response['documents'][0][0]}

def get_llm_recommendation(payload:GraphState):
    print("[System-log] evaluating the patient data using the LLM")
    #system_prompt = f"""
     #   we are performing a medical consultancy simulation. In this simulation you will act as a cardiologist and give 3 recommendations for this patient
      #  {payload['patient_id']}. you will rely on the following data:
       # {payload['heart_beat']} , {payload['systolic_bp']} and the {payload['Patient_status']}
       # Limit your answer to 3 recommendations
    #"""
    #response = ollama.chat(model = 'llama3.2:1b', messages = [{'role':'user','content':system_prompt}])
    #print('[SYSTEM-LOG] the response was generated by the llm')
    return {'llm_recommendation':'Go see a doctor'}


graph = StateGraph(GraphState)
graph.add_node('get_patient_structured_data',get_patient_structured_data)
graph.add_node('get_patient_unstructured_data',get_patient_unstructured_data)
graph.add_node('get_llm_recommendation',get_llm_recommendation)

graph.set_entry_point('get_patient_structured_data')
graph.add_edge('get_patient_structured_data','get_patient_unstructured_data')
graph.add_edge('get_patient_unstructured_data','get_llm_recommendation')

graph.add_edge('get_llm_recommendation',END)

agent_graph = graph.compile()

    






